Configuration:
    Active: true
MySQL:
    Host: localhost
    Login: 'studmine'
    Password: 'studmine'
    Database: 'studmine'
TimebetweenSaves: 30
StatsToBeRegistered:
    blockPlace: true
    blockBreak: true
    deaths: true
    timeplayed: true
    verbosity: true
